export namespace Constants {
    export const DATABASE_RETRY_COUNT = 'DATABASE_RETRY_COUNT';
    export const DATABASE_RETRY_DELAY = 'DATABASE_RETRY_DELAY';
    export const MONGODB_CONNECTION_STRING = 'MONGODB_CONNECTION_STRING';
    export const PROGRESS_DB = 'PROGRESS_DB';
    export const PROGRESS_COLLECTION = 'PROGRESS_COLLECTION';
    export const SCRAPED_DATA_DB = 'SCRAPED_DATA_DB';
    export const SCRAPED_DATA_COLLECTION = 'SCRAPED_DATA_COLLECTION';
}
