export namespace Constants {
    export const DATABASE_RETRY_COUNT = 'DATABASE_RETRY_COUNT';
    export const DATABASE_RETRY_DELAY = 'DATABASE_RETRY_DELAY';
    export const MONGODB_CONNECTION_STRING = 'MONGODB_CONNECTION_STRING';
    export const PROGRESS_DB = 'PROGRESS_DB';
    export const PROGRESS_COLLECTION = 'PROGRESS_COLLECTION';
    export const SCRAPED_DATA_DB = 'SCRAPED_DATA_DB';
    export const SCRAPED_DATA_COLLECTION = 'SCRAPED_DATA_COLLECTION';
    export const S3_ACCESS_KEY_ID = 'S3_ACCESS_KEY_ID';
    export const S3_BUCKET_NAME = 'S3_BUCKET_NAME';
    export const S3_SECRET_ACCESS_KEY = 'S3_SECRET_ACCESS_KEY';
    export const S3_REGION_NAME = 'S3_REGION_NAME';
}
